In [1]:
grid = [[0,0,0,0,0,0,0,7,2],
       [0,0,0,0,4,9,8,0,0],
       [3,1,0,0,0,0,0,0,0],
       [0,0,0,0,0,0,4,0,0],
       [0,0,4,1,0,0,7,0,0],
       [1,6,0,3,0,0,0,2,0],
       [6,0,0,0,5,0,0,0,4],
       [5,0,0,2,0,0,0,0,0],
       [0,0,8,0,0,0,0,0,0]]

In [2]:
import numpy as np
print(np.matrix(grid))

[[0 0 0 0 0 0 0 7 2]
 [0 0 0 0 4 9 8 0 0]
 [3 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 4 0 0]
 [0 0 4 1 0 0 7 0 0]
 [1 6 0 3 0 0 0 2 0]
 [6 0 0 0 5 0 0 0 4]
 [5 0 0 2 0 0 0 0 0]
 [0 0 8 0 0 0 0 0 0]]


In [3]:
def possible(y, x, n):
    global grid
    # Check Row
    for i in range(0,9):
        if grid[y][i] == n:
            return False
    
    # Check column
    for i in range(0,9):
        if grid[i][x] == n:
            return False
    
    # Check box
    x0 = (x//3)*3 
    y0 = (y//3)*3
    for i in range(0,3):
        for j in range(0, 3):
            if grid[y0+i][x0+j] == n:
                return False
    return True
possible(4, 4, 5)

False

In [4]:
possible(5, 5, 9)

False

In [6]:
def sol():
    global grid
    for y in range(9):
        for x in range(9):
            if grid[y][x] == 0:          # <-- find the empty spot, in this case '0' is the empty spot
                for n in range(1, 10):
                    if possible(y,x,n):
                        grid[y][x] = n
                        sol()
                        grid[y][x] = 0   #  <-- backtracking
                return
    print(np.matrix(grid))
    input("More?")                       # by pressing return it will give different possible solutions

In [ ]:
sol()