In [4]:
board = [[2,9,0,8,7,3,0,1,0],
       [4,0,0,0,0,5,9,2,0],
       [0,1,0,0,2,4,0,0,0],
       [0,0,0,0,8,9,6,0,0],
       [0,0,4,0,0,0,8,3,0],
       [0,8,2,3,1,0,5,0,0],
       [0,0,9,2,3,8,0,0,7],
       [8,0,0,0,4,7,0,0,0],
       [3,0,5,0,9,0,2,8,4]]
print(board)

[[2, 9, 0, 8, 7, 3, 0, 1, 0], [4, 0, 0, 0, 0, 5, 9, 2, 0], [0, 1, 0, 0, 2, 4, 0, 0, 0], [0, 0, 0, 0, 8, 9, 6, 0, 0], [0, 0, 4, 0, 0, 0, 8, 3, 0], [0, 8, 2, 3, 1, 0, 5, 0, 0], [0, 0, 9, 2, 3, 8, 0, 0, 7], [8, 0, 0, 0, 4, 7, 0, 0, 0], [3, 0, 5, 0, 9, 0, 2, 8, 4]]


In [5]:
def solve(bo):
    
    find = find_empty(bo)
    if not find:
        return True
    else:
        row, col = find
    for i in range(1, 10):
        if valid(bo, i, (row, col)):
            bo[row][col] = i
            
            if solve(bo):
                return True
            
            bo[row][col] = 0  # it will backtract if 1-9 is not valid for a position
    return False

In [6]:
def valid(bo, num, pos):   # num = number that we just added, pos = position, bo = board
    # check row
    for i in range(len(bo[0])):
        if bo[pos[0]][i] == num and pos[1] != i:
            return False
    
    # check column
    for i in range(len(bo)):
        if bo[i][pos[1]] == num and pos[0] != i:
            return False
    
    # check box
    box_x = pos[1] // 3
    box_y = pos[0] // 3
    
    for i in range(box_y*3, box_y*3 + 3):
        for j in range(box_x*3, box_x*3 + 3):
            if bo[i][j] == num and (i,j) != pos:
                return False
    return True

In [7]:
# going to differentiate between square block
def print_board(bo):
    for i in range(len(bo)):
        if i % 3 == 0 and i != 0:
            print("----------------")
        
        for j in range(len(bo[0])):
            if j % 3 == 0 and j != 0:
                print(" | ", end="")
                
            if j == 8:
                print(bo[i][j])
            else:
                print(str(bo[i][j]) + "", end="")

print_board(board)

290 | 873 | 010
400 | 005 | 920
010 | 024 | 000
----------------
000 | 089 | 600
004 | 000 | 830
082 | 310 | 500
----------------
009 | 238 | 007
800 | 047 | 000
305 | 090 | 284


In [8]:
def find_empty(bo):
    for i in range(len(bo)):
        for j in range(len(bo[0])):
            if bo[i][j] == 0:
                return (i, j)  # row, column
    return None

In [9]:
print_board(board)
solve(board)
print("Solved Sudoku:")
print_board(board)

290 | 873 | 010
400 | 005 | 920
010 | 024 | 000
----------------
000 | 089 | 600
004 | 000 | 830
082 | 310 | 500
----------------
009 | 238 | 007
800 | 047 | 000
305 | 090 | 284
Solved Sudoku:
296 | 873 | 415
437 | 165 | 928
518 | 924 | 763
----------------
153 | 489 | 672
964 | 752 | 831
782 | 316 | 549
----------------
649 | 238 | 157
821 | 547 | 396
375 | 691 | 284


In [2]:
grid = [[0,0,0,0,0,0,0,7,2],
       [0,0,0,0,4,9,8,0,0],
       [3,1,0,0,0,0,0,0,0],
       [0,0,0,0,0,0,4,0,0],
       [0,0,4,1,0,0,7,0,0],
       [1,6,0,3,0,0,0,2,0],
       [6,0,0,0,5,0,0,0,4],
       [5,0,0,2,0,0,0,0,0],
       [0,0,8,0,0,0,0,0,0]]

In [3]:
import numpy as np
print(np.matrix(grid))

[[0 0 0 0 0 0 0 7 2]
 [0 0 0 0 4 9 8 0 0]
 [3 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 4 0 0]
 [0 0 4 1 0 0 7 0 0]
 [1 6 0 3 0 0 0 2 0]
 [6 0 0 0 5 0 0 0 4]
 [5 0 0 2 0 0 0 0 0]
 [0 0 8 0 0 0 0 0 0]]


In [13]:
def possible(y, x, n):
    global grid
    # Check Row
    for i in range(0,9):
        if grid[y][i] == n:
            return False
    
    # Check column
    for i in range(0,9):
        if grid[i][x] == n:
            return False
    
    # Check box
    x0 = (x//3)*3 
    y0 = (y//3)*3
    for i in range(0,3):
        for j in range(0, 3):
            if grid[y0+i][x0+j] == n:
                return False
    return True
possible(4, 4, 5)

False

In [11]:
possible(5, 5, 9)

False

In [14]:
def sol():
    global grid
    for y in range(9):
        for x in range(9):
            if grid[y][x] == 0:          # <-- find the empty spot, in this case '0' is the empty spot
                for n in range(1, 10):
                    if possible(y,x,n):
                        grid[y][x] = n
                        sol()
                        grid[y][x] = 0   #  <-- backtracking
                return
    print(np.matrix(grid))
    input("More?")

In [ ]:
sol()

[[4 8 5 6 1 3 9 7 2]
 [2 7 6 5 4 9 8 1 3]
 [3 1 9 7 2 8 6 4 5]
 [8 2 3 9 7 5 4 6 1]
 [9 5 4 1 6 2 7 3 8]
 [1 6 7 3 8 4 5 2 9]
 [6 3 2 8 5 7 1 9 4]
 [5 4 1 2 9 6 3 8 7]
 [7 9 8 4 3 1 2 5 6]]
More?stop
[[4 8 5 6 1 3 9 7 2]
 [2 7 6 5 4 9 8 1 3]
 [3 1 9 7 2 8 6 4 5]
 [8 3 2 9 7 5 4 6 1]
 [9 5 4 1 6 2 7 3 8]
 [1 6 7 3 8 4 5 2 9]
 [6 2 1 8 5 7 3 9 4]
 [5 4 3 2 9 6 1 8 7]
 [7 9 8 4 3 1 2 5 6]]
